# Generated by Django 4.2.1 on 2023-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название расхода')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Дополнительные расходы',
                'verbose_name_plural': 'Дополнительные расходы',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='additional_expences',
            field=models.ManyToManyField(to='catalog.tourexp', verbose_name='Дополнительные расходы'),
        ),
    ]
